### ISSUE TITLE
Start tagging releases again

### ISSUE THREAD

**Issue by ghost** [Troddel/RacketGhost#39]

**Comment by mrksbrg** [comment]
That's a reasonable request! I'll follow your advice - tagging releases from now on.

**Comment by mrksbrg** [comment]
Release v.1.8.0 tagged.

**Comment by ghost** [comment]
Thanks, but 1.8.0 tag doesnt have an updated versioncode, a commit later versioncode is updated along with a version name of 1.8.1 but no tag :)

**Comment by mrksbrg** [comment]
Hmm... I realize I probably don't follow standard tagging practice then.

Isn't a tag just something indicating that a snap shot of the code is worth referring to? I.e., everything released as version 1.8.0 has that corresponding tag, but everything committed since then is "untagged" until a new tag is introduced? Or is the 1.8.0 tag alive until another tag replaces it?

If you of any relevant references, I'd be happy to read up on proper tagging!

**Comment by ghost** [comment]
Well, a tag is a "named commit". What that means for the developer or user, is something to be agreed upon. You can have multiple tags, like tagging a release, tagging snapshots for testing etc. I / we at F-Droid are interested in tagged release, so we can easily identify which version of an app is meant to be ready for the public (or at least builds cleanly).

Enter Android: Android itself is not a ware how you organize your sourcecode or releases. It doesn't know of tags, commits or branches. It only knows `package id`,  `version name`, `version code` and `signature`. If an app has the same package id as an installed app, is signed by the same key and the versioncode is higher, it's an update -- no matter if it's a "release".

So, what I was asking is to forge this two things together, to bind a tag to a specific version code/name. So every time you think development reached a stable point, update the version code and version name and tag that commit.

Sorry for being not clear enough, but I am not a native speaker. I hope this post makes things more comprehensible for you :). If not, just ping me again,

**Comment by mrksbrg** [comment]
Alright, thanks! I guess I should make sure the release tag always matches the version code in the repo then. Shouldn't be a problem, I'll just make sure to increment it at the same time as I tag a release.
